///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////

`define COVER_ZCA
covergroup Zca_c_add_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cmp_rs1_rs2_nx0 : coverpoint ins.get_gpr_reg(ins.current.rs1)  iff (ins.current.rs1 == ins.current.rs2 & ins.trap == 0 )  {
        // Compare assignments of all 31 registers excluding x0
        ignore_bins x0 = {x0};
    }

    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    // c.add with rd = 0, rs2 != 0 is a hint
    cp_c_hint_add : coverpoint ins.get_gpr_reg(ins.current.rs2) iff (ins.trap == 0 && ins.get_gpr_reg(ins.current.rd) == x0) {
        bins rs2 = {[x1:x31]}; // rs2 != 0
    }

    cp_rs1_edges : coverpoint unsigned'(ins.current.rs1_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero  = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs1_nx0 : coverpoint ins.get_gpr_reg(ins.current.rs1) iff (ins.trap == 0) {
        // RS1 register assignment (excluding x0)
        ignore_bins x0 = {x0};
    }

    cp_rs2_edges : coverpoint unsigned'(ins.current.rs2_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero     = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs2_nx0 : coverpoint ins.get_gpr_reg(ins.current.rs2)  iff (ins.trap == 0 )  {
        // RS2 register assignment (excluding x0)
        ignore_bins x0 = {x0};
    }

    cr_rs1_rs2_edges : cross cp_rs1_edges,cp_rs2_edges  iff (ins.trap == 0 )  {
        // Cross coverage of RS1 edges and RS2 edges
    }

endgroup
// ---------------------
covergroup Zca_c_addi_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    // c.addi with rd != 0, imm = 0 is a hint
    cp_c_hint_addi : coverpoint ins.get_gpr_reg(ins.current.rd) iff (ins.trap == 0 && ins.current.imm == 0) {
        bins rd[] = {[x1:x31]}; // rd != x0
    }

    cp_rs1_edges : coverpoint unsigned'(ins.current.rs1_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero  = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs1_nx0 : coverpoint ins.get_gpr_reg(ins.current.rs1) iff (ins.trap == 0) {
        // RS1 register assignment (excluding x0)
        ignore_bins x0 = {x0};
    }

    cp_imm_edges_6bit_n0 : coverpoint signed'(ins.current.imm)  iff (ins.trap == 0 )  {
        bins b_1 = {1};
        bins b_2 = {2};
        bins b_3 = {3};
        bins b_4 = {4};
        bins b_8 = {8};
        bins b_16 = {16};
        bins b_30 = {30};
        bins b_31 = {31};
        bins b_32 = {-32};
        bins b_33 = {-31};
        bins b_62 = {-2};
        bins b_63 = {-1};
    }
    cr_rs1_imm_edges_6bit_n0 : cross cp_rs1_edges,cp_imm_edges_6bit_n0  iff (ins.trap == 0 )  {
        // Cross coverage of RS1 andedges
    }

endgroup
// ---------------------
covergroup Zca_c_addi16sp_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_imm_mul_addi16sp : coverpoint signed'(ins.current.imm) iff (ins.trap == 0) {
        // Immediate Multiples of 16
        bins offset[] = {[-512:496]} with (item % 16 == 0);
        ignore_bins zero = {0};
    }

endgroup
// ---------------------
covergroup Zca_c_addi4spn_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_imm_mul_addi4spn : coverpoint ins.current.imm iff (ins.trap == 0) {
        // Immediate Multiples of 4
        bins offset[] = {[4:1020]} with (item % 4 == 0);
    }

    cp_rd_p : coverpoint ins.get_gpr_c_reg(ins.current.rd)  iff (ins.trap == 0 )  {
        // RD register assignment
    }

endgroup
// ---------------------
covergroup Zca_c_and_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cmp_rs1_rs2_c : coverpoint ins.get_gpr_c_reg(ins.current.rs1)  iff (ins.current.rs1 == ins.current.rs2 & ins.trap == 0 )  {
        // RD and RS2 register (assignment) WAR Hazard
    }

    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_rs1_edges : coverpoint unsigned'(ins.current.rs1_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero  = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs1_p : coverpoint ins.get_gpr_c_reg(ins.current.rs1)  iff (ins.trap == 0 )  {
        // RS1 register assignment
    }

    cp_rs2_edges : coverpoint unsigned'(ins.current.rs2_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero     = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs2_p : coverpoint ins.get_gpr_c_reg(ins.current.rs2)  iff (ins.trap == 0 )  {
        // RS2 register assignment
    }

    cr_rs1_rs2_edges : cross cp_rs1_edges,cp_rs2_edges  iff (ins.trap == 0 )  {
        // Cross coverage of RS1 edges and RS2 edges
    }

endgroup
// ---------------------
covergroup Zca_c_andi_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_rs1_edges : coverpoint unsigned'(ins.current.rs1_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero  = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs1_p : coverpoint ins.get_gpr_c_reg(ins.current.rs1)  iff (ins.trap == 0 )  {
        // RS1 register assignment
    }

    cp_imm_edges_6bit : coverpoint signed'(ins.current.imm)  iff (ins.trap == 0 )  {
        bins b_0 = {0};
        bins b_1 = {1};
        bins b_2 = {2};
        bins b_3 = {3};
        bins b_4 = {4};
        bins b_8 = {8};
        bins b_16 = {16};
        bins b_30 = {30};
        bins b_31 = {31};
        bins b_32 = {-32};
        bins b_33 = {-31};
        bins b_62 = {-2};
        bins b_63 = {-1};
    }
    cr_rs1_imm_edges_6bit : cross cp_rs1_edges,cp_imm_edges_6bit  iff (ins.trap == 0 )  {
        // Cross coverage of RS1 and Imm edges
    }

endgroup
// ---------------------
covergroup Zca_c_beqz_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_offset : coverpoint signed'(ins.current.imm)  iff (ins.trap == 0 )  {
        // Branch Immediate Offset value
        bins neg  = {[$:-1]};
        bins pos  = {[1:$]};
    }

    cp_rs1_edges : coverpoint unsigned'(ins.current.rs1_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero  = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs1_p : coverpoint ins.get_gpr_c_reg(ins.current.rs1)  iff (ins.trap == 0 )  {
        // RS1 register assignment
    }

endgroup
// ---------------------
covergroup Zca_c_bnez_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_offset : coverpoint signed'(ins.current.imm)  iff (ins.trap == 0 )  {
        // Branch Immediate Offset value
        bins neg  = {[$:-1]};
        bins pos  = {[1:$]};
    }

    cp_rs1_edges : coverpoint unsigned'(ins.current.rs1_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero  = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs1_p : coverpoint ins.get_gpr_c_reg(ins.current.rs1)  iff (ins.trap == 0 )  {
        // RS1 register assignment
    }

endgroup
// ---------------------
covergroup Zca_c_j_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_imm_edges_c_jal : coverpoint signed'(ins.current.imm)  iff (ins.trap == 0 )  {
        // imm is the jump offset
        // Adding a range to account for signature logic (32 bytes)
        bins b_2     = {2};
        bins b_4     = {4};
        bins b_8     = {8};
        bins b_16    = {16};
        bins b_32    = {32};
        bins b_64    = {64};
        bins b_128   = {[96:128]};
        bins b_256   = {[224:256]};
        bins b_512   = {[480:512]};
        bins b_1024  = {[992:1024]};
        bins b_m2    = {-2};
        bins b_m4    = {-4};
        bins b_m8    = {-8};
        bins b_m16   = {-16};
        bins b_m32   = {[-60:-32]};
        bins b_m64   = {[-96:-64]};
        bins b_m128  = {[-160:-128]};
        bins b_m256  = {[-288:-256]};
        bins b_m512  = {[-544:-512]};
        bins b_m1024 = {[-1056:-1024]};
        bins b_m2048 = {-2048};
    }

    cp_offset : coverpoint signed'(ins.current.imm)  iff (ins.trap == 0 )  {
        // Branch Immediate Offset value
        bins neg  = {[$:-1]};
        bins pos  = {[1:$]};
    }

endgroup
// ---------------------
covergroup Zca_c_jalr_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_offset : coverpoint signed'(ins.current.rs1_val) - ins.get_pc() iff (ins.trap == 0 )  {
        // c.jalr / c.jr destination in rs1
        bins neg  = {[$:-1]};
        bins pos  = {[1:$]};
    }
    cp_offset_lsbs : coverpoint ins.current.rs1_val[1:0]  iff (ins.trap == 0 )  {
        // c.jalr / c.jr destination is a multiple of 4 + 0/1/2/3
    }

    cp_rs1_nx0 : coverpoint ins.get_gpr_reg(ins.current.rs1) iff (ins.trap == 0) {
        // RS1 register assignment (excluding x0)
        ignore_bins x0 = {x0};
    }

endgroup
// ---------------------
covergroup Zca_c_jr_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_offset : coverpoint signed'(ins.current.rs1_val) - ins.get_pc() iff (ins.trap == 0 )  {
        // c.jalr / c.jr destination in rs1
        bins neg  = {[$:-1]};
        bins pos  = {[1:$]};
    }
    cp_offset_lsbs : coverpoint ins.current.rs1_val[1:0]  iff (ins.trap == 0 )  {
        // c.jalr / c.jr destination is a multiple of 4 + 0/1/2/3
    }

    cp_rs1_nx0 : coverpoint ins.get_gpr_reg(ins.current.rs1) iff (ins.trap == 0) {
        // RS1 register assignment (excluding x0)
        ignore_bins x0 = {x0};
    }

endgroup
// ---------------------
covergroup Zca_c_li_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    // c.li with rd = 0 is a hint
    cp_c_hint_li : coverpoint signed'(ins.current.imm) iff (ins.trap == 0 && ins.get_gpr_reg(ins.current.rd) == x0) {
        bins imm[] = {[-32:31]};
    }

    cp_imm_edges_6bit : coverpoint signed'(ins.current.imm)  iff (ins.trap == 0 )  {
        bins b_0 = {0};
        bins b_1 = {1};
        bins b_2 = {2};
        bins b_3 = {3};
        bins b_4 = {4};
        bins b_8 = {8};
        bins b_16 = {16};
        bins b_30 = {30};
        bins b_31 = {31};
        bins b_32 = {-32};
        bins b_33 = {-31};
        bins b_62 = {-2};
        bins b_63 = {-1};
    }

    cp_rs1_nx0 : coverpoint ins.get_gpr_reg(ins.current.rs1) iff (ins.trap == 0) {
        // RS1 register assignment (excluding x0)
        ignore_bins x0 = {x0};
    }

endgroup
// ---------------------
covergroup Zca_c_lui_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    // c.lui with rd = 0, imm != 0 is a hint
    cp_c_hint_lui : coverpoint signed'(ins.current.imm) iff (ins.trap == 0 && ins.get_gpr_reg(ins.current.rd) == x0) {
        bins imm[] = {[-32:31]};
        ignore_bins zero = {0};
    }

    cp_imm_edges_6bit_n0 : coverpoint signed'(ins.current.imm)  iff (ins.trap == 0 )  {
        bins b_1 = {1};
        bins b_2 = {2};
        bins b_3 = {3};
        bins b_4 = {4};
        bins b_8 = {8};
        bins b_16 = {16};
        bins b_30 = {30};
        bins b_31 = {31};
        bins b_32 = {-32};
        bins b_33 = {-31};
        bins b_62 = {-2};
        bins b_63 = {-1};
    }

    cp_rs1_nx2 : coverpoint ins.get_gpr_reg(ins.current.rs1) iff (ins.trap == 0) {
        // RS1 register assignment (excluding x0 and x2)
        ignore_bins x0 = {x0};
        ignore_bins x2 = {x2};
    }

endgroup
// ---------------------
covergroup Zca_c_lw_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cmp_rd_rs1_c : coverpoint ins.get_gpr_c_reg(ins.current.rd)  iff (ins.current.rd == ins.current.rs1 & ins.trap == 0 )  {
        // RD and RS1 register (assignment) WAR Hazard
    }

    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_imm_mul : coverpoint ins.current.imm iff (ins.trap == 0) {
        // Immediate Multiples of 4
        bins offset[] = {[0:124]} with (item % 4 == 0);
    }

    cp_rd_p : coverpoint ins.get_gpr_c_reg(ins.current.rd)  iff (ins.trap == 0 )  {
        // RD register assignment
    }

    cp_rs1_p : coverpoint ins.get_gpr_c_reg(ins.current.rs1)  iff (ins.trap == 0 )  {
        // RS1 register assignment
    }

endgroup
// ---------------------
covergroup Zca_c_lwsp_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_imm_mul_4sp : coverpoint ins.current.imm iff (ins.trap == 0) {
        // Immediate Multiples of 4
        bins offset[] = {[0:252]} with (item % 4 == 0);
    }

    cp_rd_nx0 : coverpoint ins.get_gpr_reg(ins.current.rd) iff (ins.trap == 0) {
        // RD register assignment (excluding x0)
        ignore_bins x0 = {x0};
    }

endgroup
// ---------------------
covergroup Zca_c_mv_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cmp_rs1_rs2_nx0 : coverpoint ins.get_gpr_reg(ins.current.rs1)  iff (ins.current.rs1 == ins.current.rs2 & ins.trap == 0 )  {
        // Compare assignments of all 31 registers excluding x0
        ignore_bins x0 = {x0};
    }

    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    // c.mv with rd = 0, rs2 != 0 is a hint
    cp_c_hint_mv : coverpoint ins.get_gpr_reg(ins.current.rs2) iff (ins.trap == 0 && ins.get_gpr_reg(ins.current.rd) == x0) {
        bins rs2[] = {[x1:x31]}; // rs2 != 0
    }

    cp_rd_nx0 : coverpoint ins.get_gpr_reg(ins.current.rd) iff (ins.trap == 0) {
        // RD register assignment (excluding x0)
        ignore_bins x0 = {x0};
    }

    cp_rs2_edges : coverpoint unsigned'(ins.current.rs2_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero     = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs2_nx0 : coverpoint ins.get_gpr_reg(ins.current.rs2)  iff (ins.trap == 0 )  {
        // RS2 register assignment (excluding x0)
        ignore_bins x0 = {x0};
    }

endgroup
// ---------------------
covergroup Zca_c_nop_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count_nop : coverpoint 1'b1 iff (ins.trap == 0 && ins.current.imm == 0) {
        // Number of times the canonical c.nop (imm == 0) is executed
        bins count[] = {1};
    }

    // c.nop with imm != 0 is a hint
    cp_c_hint_nop : coverpoint signed'(ins.current.imm) iff (ins.trap == 0) {
        bins imm[] = {[-32:31]};
        ignore_bins zero = {0};
    }

endgroup
// ---------------------
covergroup Zca_c_or_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cmp_rs1_rs2_c : coverpoint ins.get_gpr_c_reg(ins.current.rs1)  iff (ins.current.rs1 == ins.current.rs2 & ins.trap == 0 )  {
        // RD and RS2 register (assignment) WAR Hazard
    }

    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_rs1_edges : coverpoint unsigned'(ins.current.rs1_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero  = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs1_p : coverpoint ins.get_gpr_c_reg(ins.current.rs1)  iff (ins.trap == 0 )  {
        // RS1 register assignment
    }

    cp_rs2_edges : coverpoint unsigned'(ins.current.rs2_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero     = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs2_p : coverpoint ins.get_gpr_c_reg(ins.current.rs2)  iff (ins.trap == 0 )  {
        // RS2 register assignment
    }

    cr_rs1_rs2_edges : cross cp_rs1_edges,cp_rs2_edges  iff (ins.trap == 0 )  {
        // Cross coverage of RS1 edges and RS2 edges
    }

endgroup
// ---------------------
covergroup Zca_c_slli_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_rs1_edges : coverpoint unsigned'(ins.current.rs1_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero  = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs1_nx0 : coverpoint ins.get_gpr_reg(ins.current.rs1) iff (ins.trap == 0) {
        // RS1 register assignment (excluding x0)
        ignore_bins x0 = {x0};
    }

    cp_uimm_n0 : coverpoint unsigned'(ins.current.imm)  iff (ins.trap == 0 )  {
        bins uimm[] = {[1:`UDB_MXLEN - 1]}; // 5/6 bit immediates, skip 0
    }

    cp_imm_edges_c : coverpoint unsigned'(ins.current.imm[5:0])  iff (ins.trap == 0 )  {
        bins b_1 = {1};
        bins b_2 = {2};
        bins b_3 = {3};
        bins b_4 = {4};
        bins b_8 = {8};
        bins b_14 = {14};
        bins b_15 = {15};
        bins b_16 = {16};
        bins b_17 = {17};
        bins b_30 = {30};
        bins b_31 = {31};
        `ifdef UDB_MXLEN_64
            bins b_32 = {32};
            bins b_33 = {33};
            bins b_48 = {48};
            bins b_62 = {62};
            bins b_63 = {63};
        `endif
    }
    cr_rs1_imm_edges_c : cross cp_rs1_edges,cp_imm_edges_c  iff (ins.trap == 0 )  {
        // Cross coverage of RS1 and Imm edges
    }

endgroup
// ---------------------
covergroup Zca_c_srai_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_rs1_edges : coverpoint unsigned'(ins.current.rs1_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero  = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs1_p : coverpoint ins.get_gpr_c_reg(ins.current.rs1)  iff (ins.trap == 0 )  {
        // RS1 register assignment
    }

    cp_uimm_n0 : coverpoint unsigned'(ins.current.imm)  iff (ins.trap == 0 )  {
        bins uimm[] = {[1:`UDB_MXLEN - 1]}; // 5/6 bit immediates, skip 0
    }

    cp_imm_edges_c : coverpoint unsigned'(ins.current.imm[5:0])  iff (ins.trap == 0 )  {
        bins b_1 = {1};
        bins b_2 = {2};
        bins b_3 = {3};
        bins b_4 = {4};
        bins b_8 = {8};
        bins b_14 = {14};
        bins b_15 = {15};
        bins b_16 = {16};
        bins b_17 = {17};
        bins b_30 = {30};
        bins b_31 = {31};
        `ifdef UDB_MXLEN_64
            bins b_32 = {32};
            bins b_33 = {33};
            bins b_48 = {48};
            bins b_62 = {62};
            bins b_63 = {63};
        `endif
    }
    cr_rs1_imm_edges_c : cross cp_rs1_edges,cp_imm_edges_c  iff (ins.trap == 0 )  {
        // Cross coverage of RS1 and Imm edges
    }

endgroup
// ---------------------
covergroup Zca_c_srli_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_rs1_edges : coverpoint unsigned'(ins.current.rs1_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero  = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs1_p : coverpoint ins.get_gpr_c_reg(ins.current.rs1)  iff (ins.trap == 0 )  {
        // RS1 register assignment
    }

    cp_uimm_n0 : coverpoint unsigned'(ins.current.imm)  iff (ins.trap == 0 )  {
        bins uimm[] = {[1:`UDB_MXLEN - 1]}; // 5/6 bit immediates, skip 0
    }

    cp_imm_edges_c : coverpoint unsigned'(ins.current.imm[5:0])  iff (ins.trap == 0 )  {
        bins b_1 = {1};
        bins b_2 = {2};
        bins b_3 = {3};
        bins b_4 = {4};
        bins b_8 = {8};
        bins b_14 = {14};
        bins b_15 = {15};
        bins b_16 = {16};
        bins b_17 = {17};
        bins b_30 = {30};
        bins b_31 = {31};
        `ifdef UDB_MXLEN_64
            bins b_32 = {32};
            bins b_33 = {33};
            bins b_48 = {48};
            bins b_62 = {62};
            bins b_63 = {63};
        `endif
    }
    cr_rs1_imm_edges_c : cross cp_rs1_edges,cp_imm_edges_c  iff (ins.trap == 0 )  {
        // Cross coverage of RS1 and Imm edges
    }

endgroup
// ---------------------
covergroup Zca_c_sub_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cmp_rs1_rs2_c : coverpoint ins.get_gpr_c_reg(ins.current.rs1)  iff (ins.current.rs1 == ins.current.rs2 & ins.trap == 0 )  {
        // RD and RS2 register (assignment) WAR Hazard
    }

    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_rs1_edges : coverpoint unsigned'(ins.current.rs1_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero  = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs1_p : coverpoint ins.get_gpr_c_reg(ins.current.rs1)  iff (ins.trap == 0 )  {
        // RS1 register assignment
    }

    cp_rs2_edges : coverpoint unsigned'(ins.current.rs2_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero     = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs2_p : coverpoint ins.get_gpr_c_reg(ins.current.rs2)  iff (ins.trap == 0 )  {
        // RS2 register assignment
    }

    cr_rs1_rs2_edges : cross cp_rs1_edges,cp_rs2_edges  iff (ins.trap == 0 )  {
        // Cross coverage of RS1 edges and RS2 edges
    }

endgroup
// ---------------------
covergroup Zca_c_sw_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_imm_mul : coverpoint ins.current.imm iff (ins.trap == 0) {
        // Immediate Multiples of 4
        bins offset[] = {[0:124]} with (item % 4 == 0);
    }

    cp_rs1_p : coverpoint ins.get_gpr_c_reg(ins.current.rs1)  iff (ins.trap == 0 )  {
        // RS1 register assignment
    }

    cp_rs2_edges : coverpoint unsigned'(ins.current.rs2_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero     = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs2_p : coverpoint ins.get_gpr_c_reg(ins.current.rs2)  iff (ins.trap == 0 )  {
        // RS2 register assignment
    }

endgroup
// ---------------------
covergroup Zca_c_swsp_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_imm_mul_4sp : coverpoint ins.current.imm iff (ins.trap == 0) {
        // Immediate Multiples of 4
        bins offset[] = {[0:252]} with (item % 4 == 0);
    }

    cp_rs2 : coverpoint ins.get_gpr_reg(ins.current.rs2)  iff (ins.trap == 0 )  {
        // RS2 register assignment
    }

    cp_rs2_edges : coverpoint unsigned'(ins.current.rs2_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero     = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

endgroup
// ---------------------
covergroup Zca_c_xor_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cmp_rs1_rs2_c : coverpoint ins.get_gpr_c_reg(ins.current.rs1)  iff (ins.current.rs1 == ins.current.rs2 & ins.trap == 0 )  {
        // RD and RS2 register (assignment) WAR Hazard
    }

    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_rs1_edges : coverpoint unsigned'(ins.current.rs1_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero  = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs1_p : coverpoint ins.get_gpr_c_reg(ins.current.rs1)  iff (ins.trap == 0 )  {
        // RS1 register assignment
    }

    cp_rs2_edges : coverpoint unsigned'(ins.current.rs2_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero     = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs2_p : coverpoint ins.get_gpr_c_reg(ins.current.rs2)  iff (ins.trap == 0 )  {
        // RS2 register assignment
    }

    cr_rs1_rs2_edges : cross cp_rs1_edges,cp_rs2_edges  iff (ins.trap == 0 )  {
        // Cross coverage of RS1 edges and RS2 edges
    }

endgroup
// ---------------------
`ifdef UDB_MXLEN_32
covergroup Zca_c_jal_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_imm_edges_c_jal : coverpoint signed'(ins.current.imm)  iff (ins.trap == 0 )  {
        // imm is the jump offset
        // Adding a range to account for signature logic (32 bytes)
        bins b_2     = {2};
        bins b_4     = {4};
        bins b_8     = {8};
        bins b_16    = {16};
        bins b_32    = {32};
        bins b_64    = {64};
        bins b_128   = {[96:128]};
        bins b_256   = {[224:256]};
        bins b_512   = {[480:512]};
        bins b_1024  = {[992:1024]};
        bins b_m2    = {-2};
        bins b_m4    = {-4};
        bins b_m8    = {-8};
        bins b_m16   = {-16};
        bins b_m32   = {[-60:-32]};
        bins b_m64   = {[-96:-64]};
        bins b_m128  = {[-160:-128]};
        bins b_m256  = {[-288:-256]};
        bins b_m512  = {[-544:-512]};
        bins b_m1024 = {[-1056:-1024]};
        bins b_m2048 = {-2048};
    }

    cp_offset : coverpoint signed'(ins.current.imm)  iff (ins.trap == 0 )  {
        // Branch Immediate Offset value
        bins neg  = {[$:-1]};
        bins pos  = {[1:$]};
    }

endgroup
// ---------------------
`endif
`ifdef UDB_MXLEN_64
covergroup Zca_c_addiw_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_rs1_edges : coverpoint unsigned'(ins.current.rs1_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero  = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs1_nx0 : coverpoint ins.get_gpr_reg(ins.current.rs1) iff (ins.trap == 0) {
        // RS1 register assignment (excluding x0)
        ignore_bins x0 = {x0};
    }

    cp_imm_edges_6bit : coverpoint signed'(ins.current.imm)  iff (ins.trap == 0 )  {
        bins b_0 = {0};
        bins b_1 = {1};
        bins b_2 = {2};
        bins b_3 = {3};
        bins b_4 = {4};
        bins b_8 = {8};
        bins b_16 = {16};
        bins b_30 = {30};
        bins b_31 = {31};
        bins b_32 = {-32};
        bins b_33 = {-31};
        bins b_62 = {-2};
        bins b_63 = {-1};
    }
    cr_rs1_imm_edges_6bit : cross cp_rs1_edges,cp_imm_edges_6bit  iff (ins.trap == 0 )  {
        // Cross coverage of RS1 and Imm edges
    }

endgroup
// ---------------------
covergroup Zca_c_addw_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cmp_rs1_rs2_c : coverpoint ins.get_gpr_c_reg(ins.current.rs1)  iff (ins.current.rs1 == ins.current.rs2 & ins.trap == 0 )  {
        // RD and RS2 register (assignment) WAR Hazard
    }

    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_rs1_edges : coverpoint unsigned'(ins.current.rs1_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero  = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs1_p : coverpoint ins.get_gpr_c_reg(ins.current.rs1)  iff (ins.trap == 0 )  {
        // RS1 register assignment
    }

    cp_rs2_edges : coverpoint unsigned'(ins.current.rs2_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero     = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs2_p : coverpoint ins.get_gpr_c_reg(ins.current.rs2)  iff (ins.trap == 0 )  {
        // RS2 register assignment
    }

    cr_rs1_rs2_edges : cross cp_rs1_edges,cp_rs2_edges  iff (ins.trap == 0 )  {
        // Cross coverage of RS1 edges and RS2 edges
    }

endgroup
// ---------------------
covergroup Zca_c_ld_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cmp_rd_rs1_c : coverpoint ins.get_gpr_c_reg(ins.current.rd)  iff (ins.current.rd == ins.current.rs1 & ins.trap == 0 )  {
        // RD and RS1 register (assignment) WAR Hazard
    }

    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_imm_mul_8 : coverpoint ins.current.imm iff (ins.trap == 0) {
        // Immediate Multiples of 8
        bins offset[] = {[0:248]} with (item % 8 == 0);
    }

    cp_rd_p : coverpoint ins.get_gpr_c_reg(ins.current.rd)  iff (ins.trap == 0 )  {
        // RD register assignment
    }

    cp_rs1_p : coverpoint ins.get_gpr_c_reg(ins.current.rs1)  iff (ins.trap == 0 )  {
        // RS1 register assignment
    }

endgroup
// ---------------------
covergroup Zca_c_ldsp_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_imm_mul_8sp : coverpoint ins.current.imm iff (ins.trap == 0) {
        // Immediate Multiples of 8
        bins offset[] = {[0:504]} with (item % 8 == 0);
    }

    cp_rd_nx0 : coverpoint ins.get_gpr_reg(ins.current.rd) iff (ins.trap == 0) {
        // RD register assignment (excluding x0)
        ignore_bins x0 = {x0};
    }

endgroup
// ---------------------
covergroup Zca_c_sd_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_imm_mul_8 : coverpoint ins.current.imm iff (ins.trap == 0) {
        // Immediate Multiples of 8
        bins offset[] = {[0:248]} with (item % 8 == 0);
    }

    cp_rs1_p : coverpoint ins.get_gpr_c_reg(ins.current.rs1)  iff (ins.trap == 0 )  {
        // RS1 register assignment
    }

    cp_rs2_edges : coverpoint unsigned'(ins.current.rs2_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero     = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs2_p : coverpoint ins.get_gpr_c_reg(ins.current.rs2)  iff (ins.trap == 0 )  {
        // RS2 register assignment
    }

endgroup
// ---------------------
covergroup Zca_c_sdsp_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_imm_mul_8sp : coverpoint ins.current.imm iff (ins.trap == 0) {
        // Immediate Multiples of 8
        bins offset[] = {[0:504]} with (item % 8 == 0);
    }

    cp_rs2 : coverpoint ins.get_gpr_reg(ins.current.rs2)  iff (ins.trap == 0 )  {
        // RS2 register assignment
    }

    cp_rs2_edges : coverpoint unsigned'(ins.current.rs2_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero     = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

endgroup
// ---------------------
covergroup Zca_c_subw_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cmp_rs1_rs2_c : coverpoint ins.get_gpr_c_reg(ins.current.rs1)  iff (ins.current.rs1 == ins.current.rs2 & ins.trap == 0 )  {
        // RD and RS2 register (assignment) WAR Hazard
    }

    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_rs1_edges : coverpoint unsigned'(ins.current.rs1_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero  = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs1_p : coverpoint ins.get_gpr_c_reg(ins.current.rs1)  iff (ins.trap == 0 )  {
        // RS1 register assignment
    }

    cp_rs2_edges : coverpoint unsigned'(ins.current.rs2_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero     = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs2_p : coverpoint ins.get_gpr_c_reg(ins.current.rs2)  iff (ins.trap == 0 )  {
        // RS2 register assignment
    }

    cr_rs1_rs2_edges : cross cp_rs1_edges,cp_rs2_edges  iff (ins.trap == 0 )  {
        // Cross coverage of RS1 edges and RS2 edges
    }

endgroup
// ---------------------
`endif
function void zca_sample(int hart, int issue, ins_t ins);

    case (traceDataQ[hart][issue][0].inst_id)
        INSTR_C_ADD     : begin
            Zca_c_add_cg.sample(ins);
        end
        INSTR_C_ADDI     : begin
            Zca_c_addi_cg.sample(ins);
        end
        INSTR_C_ADDI16SP     : begin
            Zca_c_addi16sp_cg.sample(ins);
        end
        INSTR_C_ADDI4SPN     : begin
            Zca_c_addi4spn_cg.sample(ins);
        end
        INSTR_C_AND     : begin
            Zca_c_and_cg.sample(ins);
        end
        INSTR_C_ANDI     : begin
            Zca_c_andi_cg.sample(ins);
        end
        INSTR_C_BEQZ     : begin
            Zca_c_beqz_cg.sample(ins);
        end
        INSTR_C_BNEZ     : begin
            Zca_c_bnez_cg.sample(ins);
        end
        INSTR_C_J     : begin
            Zca_c_j_cg.sample(ins);
        end
        INSTR_C_JALR     : begin
            Zca_c_jalr_cg.sample(ins);
        end
        INSTR_C_JR     : begin
            Zca_c_jr_cg.sample(ins);
        end
        INSTR_C_LI     : begin
            Zca_c_li_cg.sample(ins);
        end
        INSTR_C_LUI     : begin
            Zca_c_lui_cg.sample(ins);
        end
        INSTR_C_LW     : begin
            Zca_c_lw_cg.sample(ins);
        end
        INSTR_C_LWSP     : begin
            Zca_c_lwsp_cg.sample(ins);
        end
        INSTR_C_MV     : begin
            Zca_c_mv_cg.sample(ins);
        end
        INSTR_C_NOP     : begin
            Zca_c_nop_cg.sample(ins);
        end
        INSTR_C_OR     : begin
            Zca_c_or_cg.sample(ins);
        end
        INSTR_C_SLLI     : begin
            Zca_c_slli_cg.sample(ins);
        end
        INSTR_C_SRAI     : begin
            Zca_c_srai_cg.sample(ins);
        end
        INSTR_C_SRLI     : begin
            Zca_c_srli_cg.sample(ins);
        end
        INSTR_C_SUB     : begin
            Zca_c_sub_cg.sample(ins);
        end
        INSTR_C_SW     : begin
            Zca_c_sw_cg.sample(ins);
        end
        INSTR_C_SWSP     : begin
            Zca_c_swsp_cg.sample(ins);
        end
        INSTR_C_XOR     : begin
            Zca_c_xor_cg.sample(ins);
        end
`ifdef UDB_MXLEN_32
        INSTR_C_JAL     : begin
            Zca_c_jal_cg.sample(ins);
        end
`endif
`ifdef UDB_MXLEN_64
        INSTR_C_ADDIW     : begin
            Zca_c_addiw_cg.sample(ins);
        end
        INSTR_C_ADDW     : begin
            Zca_c_addw_cg.sample(ins);
        end
        INSTR_C_LD     : begin
            Zca_c_ld_cg.sample(ins);
        end
        INSTR_C_LDSP     : begin
            Zca_c_ldsp_cg.sample(ins);
        end
        INSTR_C_SD     : begin
            Zca_c_sd_cg.sample(ins);
        end
        INSTR_C_SDSP     : begin
            Zca_c_sdsp_cg.sample(ins);
        end
        INSTR_C_SUBW     : begin
            Zca_c_subw_cg.sample(ins);
        end
`endif
    endcase
endfunction
