///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////

`define COVER_ZIHINTNTL
covergroup Zihintntl_ntl_all_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

endgroup
// ---------------------
covergroup Zihintntl_ntl_p1_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

endgroup
// ---------------------
covergroup Zihintntl_ntl_pall_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

endgroup
// ---------------------
covergroup Zihintntl_ntl_s1_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint 1'b1  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

endgroup
// ---------------------
function void zihintntl_sample(int hart, int issue, ins_t ins);

    case (traceDataQ[hart][issue][0].inst_id)
        INSTR_NTL_ALL     : begin
            Zihintntl_ntl_all_cg.sample(ins);
        end
        INSTR_NTL_P1     : begin
            Zihintntl_ntl_p1_cg.sample(ins);
        end
        INSTR_NTL_PALL     : begin
            Zihintntl_ntl_pall_cg.sample(ins);
        end
        INSTR_NTL_S1     : begin
            Zihintntl_ntl_s1_cg.sample(ins);
        end
    endcase
endfunction
