# SPDX-License-Identifier: Apache-2.0
#
# Continuous performance testing of the ACT framework with CodSpeed.

name: CodSpeed

on:
  push:
    branches:
      - main
  pull_request:
  # Allow CodSpeed to trigger backtest performance analysis to seed initial data.
  workflow_dispatch:

# Only run the latest commit for a given ref.
concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write # OpenID Connect authentication with CodSpeed

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Set up tools
        uses: ./.github/actions/setup-tools

      - name: Install dependencies
        run: uv sync --dev

      - name: Run benchmarks
        uses: CodSpeedHQ/action@a4a36bb07c0638b0b4ca52bf1f3dad1b4289e52f # v4.18.1
        with:
          mode: simulation
          run: uv run --no-sync pytest benchmarks/ --codspeed
