# jcarlin@hmc.edu 5 Nov 2025
# SPDX-License-Identifier: Apache-2.0

name: pre-commit check

on:
  push:
  pull_request:

jobs:
  lint:
    name: Pre-commit check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6

      - name: Ensure pre-commit checks pass
        run: uvx pre-commit run --all-files --show-diff-on-failure --color=always
